import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DropDownDataService {

  constructor() { }
  activityList: String[] = [
    'Account Management - Client Call',
    'Account Management - Client Email Response',
    'Accounts - Data entry work',
    'Accounts - Office work',
    'Accounts - Outside office',
    'Accounts - Statutory work',
    'Accounts - Support',
    'Accounts - Tele-calling & Online communication',
    'BA - Business/ Product/ Requirement Understanding',
    'BA - Case Study / Patents / White Papers',
    'BA - Client Interaction / Meeting',
    'BA - Conceptualization / Suggesting Value Add Features',
    'BA - Design Finalization / Review',
    'BA - Documentation',
    'BA - Feasibility / Need / Gap Analysis',
    'BA - Feature Identification / Listing / WBS',
    'BA - Problem Statement / Solution Scoping',
    'BA - Project Handover Meeting',
    'BA - R & D / Technical Reading',
    'BA - Requirement Gathering / Elicitation',
    'BA - Technical Research & Inputs to Sales Proposal / RFP',
    'BA - ThoughtBox Activities',
    'BA - Use Case Creation / User Journey / StoryBoards',
    'BA - Wireframing / Prototyping / PoC',
    'Bug Fixing',
    'Change Request',
    'Client Interaction',
    'Client Visit',
    'Code review',
    'Coding and Implementation',
    'Daily Standup Meeting',
    'Database Design',
    'DB Administration',
    'Design - Image Slicing',
    'Design - UI',
    'Design - Wireframes',
    'DevOps - Build and Release',
    'Documentation',
    'Efforts Estimation',
    'ESS Report Generation',
    'Guiding Colleague',
    'HR - Administration',
    'HR - Appraisals',
    'HR - Biometric system',
    'HR - Celebration of Festivals/Birthdays',
    'HR - Coordination',
    'HR - Documentation',
    'HR - Follow up',
    'HR - Govt. Adherence',
    'HR - Interviews',
    'HR - Joining Formalities',
    'HR - Maintained of database',
    'HR - Meetings',
    'HR - Morning Mail',
    'HR - Offer and Negotiation',
    'HR - Orientation',
    'HR - Other activities',
    'HR - Out of office work',
    'HR - Payroll',
    'HR - Personnel Files',
    'HR - Quarterly Performance ratings',
    'HR - Resourcing',
    'HR - Sage Payroll  Modules',
    'HR - Summer interns',
    'Interview',
    'Investigation issue/scenario',
    'Maintenance / Installation',
    'Marketing Design/ Editorial Design',
    'MIS Reports',
    'Others',
    'PMO Review',
    'PreSales Activity',
    'Product Design- Growth Experiments / ICE',
    'Project Management',
    'Project Planning and Analysis',
    'R & D',
    'Reports Design and Development',
    'Requirement Understanding',
    'Resource Planning',
    'Sales - Client visit',
    'Sales - Lead generation',
    'Sales - Leads Follow up',
    'Sales - Market Development Africa',
    'Sales - Market Development Australia/NZ',
    'Sales - Market Development India',
    'Sales - Market Development UK',
    'Sales - Market Development USA',
    'Sales - Marketing Campaigns',
    'Sales - Payment follow-ups',
    'Sales - Presentation',
    'Sales - Proposal making',
    'Sales - Support',
    'Sales - Tele calling',
    'SCCM',
    'Support',
    'System and Architecture Design',
    'Task Allocation',
    'Team Discussion',
    'Team Review',
    'Test Case Writing',
    'Testing',
    'Testing Review',
    'Training',
    'UI Design - Screen Designs/ Prototyping',
    'UI Dev - Accessibility',
    'UI Dev - HTML CSS/ Responsive Designs',
    'UI Dev - Java Scripts / Validation',
    'UI Dev - Testing/Debugging ',
    'UI Dev - Version Control Git',
    'UI Dev- Browser Developer Tools/ Web Performance',
    'Unit Testing',
    'UX - Cognitive Walkthrough',
    'UX - Research/ Ideation & Brainstorm/ User Journey mapping',
    'UX - Stakeholder Review',
    'UX - Technical Review',
    'UX - Usability Testing / User testing',
    "UX - Wireframing/ Crazy 8's/ Solution Sketch/ Storyboarding",
  ];
  projectList: String[] = ['ART POC - Android & IOS', 'Learning & Development'];

  themeList: String[] = [
    'Default',
    'Aqua',
    'Glass',
    'Black Glass',
    'Office2003 Blue',
    'Office2003 Olive',
    'Office2003 Silver',
    'Plastic Blue',
    'Red Wine',
    'Soft Orange',
    'Youthful',
  ];
}
